/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContextsToUseEventNavigation } from "cps-global-configuration";
export { ContextsToUseEventNavigation } from "cps-global-configuration";
export namespace Components {
    interface CpsGlobalBanner {
    }
    interface CpsGlobalCaseDetails {
    }
    interface CpsGlobalFooter {
    }
    interface CpsGlobalHeader {
        /**
          * @default false
         */
        "isDcf": boolean;
    }
    interface CpsGlobalMenu {
    }
    interface NavLink {
        "ariaSelected"?: boolean;
        "dcfContextsToUseEventNavigation"?: ContextsToUseEventNavigation;
        "disabled": boolean;
        "href": string;
        "label": string;
        "openInNewTab"?: boolean;
        "selected": boolean;
    }
}
export interface NavLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNavLinkElement;
}
declare global {
    interface HTMLCpsGlobalBannerElement extends Components.CpsGlobalBanner, HTMLStencilElement {
    }
    var HTMLCpsGlobalBannerElement: {
        prototype: HTMLCpsGlobalBannerElement;
        new (): HTMLCpsGlobalBannerElement;
    };
    interface HTMLCpsGlobalCaseDetailsElement extends Components.CpsGlobalCaseDetails, HTMLStencilElement {
    }
    var HTMLCpsGlobalCaseDetailsElement: {
        prototype: HTMLCpsGlobalCaseDetailsElement;
        new (): HTMLCpsGlobalCaseDetailsElement;
    };
    interface HTMLCpsGlobalFooterElement extends Components.CpsGlobalFooter, HTMLStencilElement {
    }
    var HTMLCpsGlobalFooterElement: {
        prototype: HTMLCpsGlobalFooterElement;
        new (): HTMLCpsGlobalFooterElement;
    };
    interface HTMLCpsGlobalHeaderElement extends Components.CpsGlobalHeader, HTMLStencilElement {
    }
    var HTMLCpsGlobalHeaderElement: {
        prototype: HTMLCpsGlobalHeaderElement;
        new (): HTMLCpsGlobalHeaderElement;
    };
    interface HTMLCpsGlobalMenuElement extends Components.CpsGlobalMenu, HTMLStencilElement {
    }
    var HTMLCpsGlobalMenuElement: {
        prototype: HTMLCpsGlobalMenuElement;
        new (): HTMLCpsGlobalMenuElement;
    };
    interface HTMLNavLinkElementEventMap {
        "cps-global-header-event": string;
    }
    interface HTMLNavLinkElement extends Components.NavLink, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNavLinkElement: {
        prototype: HTMLNavLinkElement;
        new (): HTMLNavLinkElement;
    };
    interface HTMLElementTagNameMap {
        "cps-global-banner": HTMLCpsGlobalBannerElement;
        "cps-global-case-details": HTMLCpsGlobalCaseDetailsElement;
        "cps-global-footer": HTMLCpsGlobalFooterElement;
        "cps-global-header": HTMLCpsGlobalHeaderElement;
        "cps-global-menu": HTMLCpsGlobalMenuElement;
        "nav-link": HTMLNavLinkElement;
    }
}
declare namespace LocalJSX {
    interface CpsGlobalBanner {
    }
    interface CpsGlobalCaseDetails {
    }
    interface CpsGlobalFooter {
    }
    interface CpsGlobalHeader {
        /**
          * @default false
         */
        "isDcf"?: boolean;
    }
    interface CpsGlobalMenu {
    }
    interface NavLink {
        "ariaSelected"?: boolean;
        "dcfContextsToUseEventNavigation"?: ContextsToUseEventNavigation;
        "disabled"?: boolean;
        "href"?: string;
        "label"?: string;
        "onCps-global-header-event"?: (event: NavLinkCustomEvent<string>) => void;
        "openInNewTab"?: boolean;
        "selected"?: boolean;
    }
    interface IntrinsicElements {
        "cps-global-banner": CpsGlobalBanner;
        "cps-global-case-details": CpsGlobalCaseDetails;
        "cps-global-footer": CpsGlobalFooter;
        "cps-global-header": CpsGlobalHeader;
        "cps-global-menu": CpsGlobalMenu;
        "nav-link": NavLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cps-global-banner": LocalJSX.CpsGlobalBanner & JSXBase.HTMLAttributes<HTMLCpsGlobalBannerElement>;
            "cps-global-case-details": LocalJSX.CpsGlobalCaseDetails & JSXBase.HTMLAttributes<HTMLCpsGlobalCaseDetailsElement>;
            "cps-global-footer": LocalJSX.CpsGlobalFooter & JSXBase.HTMLAttributes<HTMLCpsGlobalFooterElement>;
            "cps-global-header": LocalJSX.CpsGlobalHeader & JSXBase.HTMLAttributes<HTMLCpsGlobalHeaderElement>;
            "cps-global-menu": LocalJSX.CpsGlobalMenu & JSXBase.HTMLAttributes<HTMLCpsGlobalMenuElement>;
            "nav-link": LocalJSX.NavLink & JSXBase.HTMLAttributes<HTMLNavLinkElement>;
        }
    }
}
