/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NotificationBannerType } from "./components/cps-gds-notification-banner/cps-gds-notification-banner";
import { ContextsToUseEventNavigation } from "cps-global-configuration";
export { NotificationBannerType } from "./components/cps-gds-notification-banner/cps-gds-notification-banner";
export { ContextsToUseEventNavigation } from "cps-global-configuration";
export namespace Components {
    interface CpsGdsNotificationBanner {
        /**
          * Show only the header until the user asks for detail — the prototype's progressive enhancement, reimplemented rather than bolted on with jQuery. The toggle carries aria-expanded and aria-controls, and the content is genuinely `hidden` when collapsed, so assistive tech is told the same story the sighted user gets rather than reading content that looks closed.
          * @default false
         */
        "collapsible": boolean;
        /**
          * Prevent the banner from being focused on page load (only relevant for success type).
          * @default false
         */
        "disableAutoFocus": boolean;
        /**
          * Renders the dismiss button. Persistence is the caller's responsibility via the `cpsDismissed` event.
          * @default false
         */
        "dismissible": boolean;
        /**
          * Pin the banner to the bottom of the viewport instead of letting it sit in the document flow. Matches the UCD prototype's app-notification-banner-pinned.
          * @default false
         */
        "pinned": boolean;
        /**
          * Override the ARIA role. Defaults to "region" (or "alert" for success type).
         */
        "role"?: string;
        /**
          * The heading level for the title (1-6). Defaults to 2.
          * @default 2
         */
        "titleHeadingLevel": number;
        /**
          * Custom id for the title element. Defaults to "govuk-notification-banner-title".
          * @default "govuk-notification-banner-title"
         */
        "titleId": string;
        /**
          * The title text shown in the banner header. Defaults to "Important" or "Success" based on type.
         */
        "titleText"?: string;
        /**
          * Set to "success" for the green success variant. Omit for the default (information) variant.
         */
        "type"?: NotificationBannerType;
    }
    interface CpsGlobalBanner {
    }
    interface CpsGlobalCaseDetails {
    }
    /**
     * The interruption, from the UCD prototype's moj-interruption-card.
     * WHY NOT A MODAL <dialog>
     * showModal() is the tidy answer to "block the page accessibly" — the browser
     * inerts the whole document, traps focus and supplies a backdrop, all without
     * touching the host's DOM. But it puts the dialog in the TOP LAYER, which covers
     * everything, and the design keeps the header and footer visible. So we do it
     * ourselves: an overlay occupying the band below the header, plus `inert` on the
     * host's content.
     * WHAT `inert` BUYS
     * Covering the page visually is not enough. Without it a screen reader still
     * reads the case underneath and the keyboard still tabs into it — the user is
     * told to stop while the page quietly says otherwise. `inert` removes those
     * elements from the accessibility tree AND the tab order in one attribute.
     * WE MUTATE HOST DOM HERE, WHICH WE OTHERWISE AVOID. It is confined to setting
     * and clearing `inert` on the direct children of <body>, excluding our own root,
     * and every path that hides the overlay releases it — including
     * disconnectedCallback, because a host app that tears us down mid-interruption
     * must not be left with an unusable page.
     * ACCESSIBILITY
     * role="alertdialog" is the role for an interruption that demands a decision.
     * Focus moves into the card when it appears, so assistive tech announces it
     * rather than leaving it to be discovered, and Escape dismisses — both choices
     * are visible, so trapping the keyboard would cost more than it buys.
     */
    interface CpsGlobalCaseLockingInterstitial {
    }
    interface CpsGlobalCaseLockingNotification {
    }
    interface CpsGlobalFooter {
        "userEmail"?: string;
    }
    interface CpsGlobalFooterContent {
        "userEmail"?: string;
    }
    interface CpsGlobalHeader {
        /**
          * @default false
         */
        "isDcf": boolean;
    }
    interface CpsGlobalHomePageNotification {
    }
    interface CpsGlobalMenu {
    }
    interface CpsGlobalNotifications {
    }
    interface CpsGlobalRecentCases {
        /**
          * @default ""
         */
        "itemClass": string;
        /**
          * @default "{urn} - {description}"
         */
        "itemTextTemplate": string;
        /**
          * @default "govuk-link"
         */
        "linkClass": string;
        /**
          * @default "govuk-list govuk-list--spaced govuk-list--bullet"
         */
        "listClass": string;
    }
    interface CpsRegion {
        /**
          * Identifier passed to the central service when this region enters or leaves "present" state. Reflected so it's readable as an attribute.
         */
        "code": string;
        /**
          * Optional subject for kinds that are scoped to one — a witness, a defendant. With it the section is "<caseId>:KIND:<subjectId>"; without it the section is case-wide, "<caseId>:KIND". Must match the id the other clients use for the same person, or the two register different sections for one subject.
         */
        "subject"?: string;
    }
    interface CpsSkipLink {
        "targetSelector"?: string;
        /**
          * @default false
         */
        "useScroll": boolean;
    }
    interface CpsSkipLinks {
    }
    interface NavLink {
        "ariaSelected"?: boolean;
        "dcfContextsToUseEventNavigation"?: ContextsToUseEventNavigation;
        "disabled": boolean;
        "href": string;
        "label": string;
        "openInNewTab"?: boolean;
        "selected": boolean;
    }
}
export interface CpsGdsNotificationBannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCpsGdsNotificationBannerElement;
}
export interface NavLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNavLinkElement;
}
declare global {
    interface HTMLCpsGdsNotificationBannerElementEventMap {
        "cpsDismissed": void;
    }
    interface HTMLCpsGdsNotificationBannerElement extends Components.CpsGdsNotificationBanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCpsGdsNotificationBannerElementEventMap>(type: K, listener: (this: HTMLCpsGdsNotificationBannerElement, ev: CpsGdsNotificationBannerCustomEvent<HTMLCpsGdsNotificationBannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCpsGdsNotificationBannerElementEventMap>(type: K, listener: (this: HTMLCpsGdsNotificationBannerElement, ev: CpsGdsNotificationBannerCustomEvent<HTMLCpsGdsNotificationBannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCpsGdsNotificationBannerElement: {
        prototype: HTMLCpsGdsNotificationBannerElement;
        new (): HTMLCpsGdsNotificationBannerElement;
    };
    interface HTMLCpsGlobalBannerElement extends Components.CpsGlobalBanner, HTMLStencilElement {
    }
    var HTMLCpsGlobalBannerElement: {
        prototype: HTMLCpsGlobalBannerElement;
        new (): HTMLCpsGlobalBannerElement;
    };
    interface HTMLCpsGlobalCaseDetailsElement extends Components.CpsGlobalCaseDetails, HTMLStencilElement {
    }
    var HTMLCpsGlobalCaseDetailsElement: {
        prototype: HTMLCpsGlobalCaseDetailsElement;
        new (): HTMLCpsGlobalCaseDetailsElement;
    };
    /**
     * The interruption, from the UCD prototype's moj-interruption-card.
     * WHY NOT A MODAL <dialog>
     * showModal() is the tidy answer to "block the page accessibly" — the browser
     * inerts the whole document, traps focus and supplies a backdrop, all without
     * touching the host's DOM. But it puts the dialog in the TOP LAYER, which covers
     * everything, and the design keeps the header and footer visible. So we do it
     * ourselves: an overlay occupying the band below the header, plus `inert` on the
     * host's content.
     * WHAT `inert` BUYS
     * Covering the page visually is not enough. Without it a screen reader still
     * reads the case underneath and the keyboard still tabs into it — the user is
     * told to stop while the page quietly says otherwise. `inert` removes those
     * elements from the accessibility tree AND the tab order in one attribute.
     * WE MUTATE HOST DOM HERE, WHICH WE OTHERWISE AVOID. It is confined to setting
     * and clearing `inert` on the direct children of <body>, excluding our own root,
     * and every path that hides the overlay releases it — including
     * disconnectedCallback, because a host app that tears us down mid-interruption
     * must not be left with an unusable page.
     * ACCESSIBILITY
     * role="alertdialog" is the role for an interruption that demands a decision.
     * Focus moves into the card when it appears, so assistive tech announces it
     * rather than leaving it to be discovered, and Escape dismisses — both choices
     * are visible, so trapping the keyboard would cost more than it buys.
     */
    interface HTMLCpsGlobalCaseLockingInterstitialElement extends Components.CpsGlobalCaseLockingInterstitial, HTMLStencilElement {
    }
    var HTMLCpsGlobalCaseLockingInterstitialElement: {
        prototype: HTMLCpsGlobalCaseLockingInterstitialElement;
        new (): HTMLCpsGlobalCaseLockingInterstitialElement;
    };
    interface HTMLCpsGlobalCaseLockingNotificationElement extends Components.CpsGlobalCaseLockingNotification, HTMLStencilElement {
    }
    var HTMLCpsGlobalCaseLockingNotificationElement: {
        prototype: HTMLCpsGlobalCaseLockingNotificationElement;
        new (): HTMLCpsGlobalCaseLockingNotificationElement;
    };
    interface HTMLCpsGlobalFooterElement extends Components.CpsGlobalFooter, HTMLStencilElement {
    }
    var HTMLCpsGlobalFooterElement: {
        prototype: HTMLCpsGlobalFooterElement;
        new (): HTMLCpsGlobalFooterElement;
    };
    interface HTMLCpsGlobalFooterContentElement extends Components.CpsGlobalFooterContent, HTMLStencilElement {
    }
    var HTMLCpsGlobalFooterContentElement: {
        prototype: HTMLCpsGlobalFooterContentElement;
        new (): HTMLCpsGlobalFooterContentElement;
    };
    interface HTMLCpsGlobalHeaderElement extends Components.CpsGlobalHeader, HTMLStencilElement {
    }
    var HTMLCpsGlobalHeaderElement: {
        prototype: HTMLCpsGlobalHeaderElement;
        new (): HTMLCpsGlobalHeaderElement;
    };
    interface HTMLCpsGlobalHomePageNotificationElement extends Components.CpsGlobalHomePageNotification, HTMLStencilElement {
    }
    var HTMLCpsGlobalHomePageNotificationElement: {
        prototype: HTMLCpsGlobalHomePageNotificationElement;
        new (): HTMLCpsGlobalHomePageNotificationElement;
    };
    interface HTMLCpsGlobalMenuElement extends Components.CpsGlobalMenu, HTMLStencilElement {
    }
    var HTMLCpsGlobalMenuElement: {
        prototype: HTMLCpsGlobalMenuElement;
        new (): HTMLCpsGlobalMenuElement;
    };
    interface HTMLCpsGlobalNotificationsElement extends Components.CpsGlobalNotifications, HTMLStencilElement {
    }
    var HTMLCpsGlobalNotificationsElement: {
        prototype: HTMLCpsGlobalNotificationsElement;
        new (): HTMLCpsGlobalNotificationsElement;
    };
    interface HTMLCpsGlobalRecentCasesElement extends Components.CpsGlobalRecentCases, HTMLStencilElement {
    }
    var HTMLCpsGlobalRecentCasesElement: {
        prototype: HTMLCpsGlobalRecentCasesElement;
        new (): HTMLCpsGlobalRecentCasesElement;
    };
    interface HTMLCpsRegionElement extends Components.CpsRegion, HTMLStencilElement {
    }
    var HTMLCpsRegionElement: {
        prototype: HTMLCpsRegionElement;
        new (): HTMLCpsRegionElement;
    };
    interface HTMLCpsSkipLinkElement extends Components.CpsSkipLink, HTMLStencilElement {
    }
    var HTMLCpsSkipLinkElement: {
        prototype: HTMLCpsSkipLinkElement;
        new (): HTMLCpsSkipLinkElement;
    };
    interface HTMLCpsSkipLinksElement extends Components.CpsSkipLinks, HTMLStencilElement {
    }
    var HTMLCpsSkipLinksElement: {
        prototype: HTMLCpsSkipLinksElement;
        new (): HTMLCpsSkipLinksElement;
    };
    interface HTMLNavLinkElementEventMap {
        "cps-global-header-event": string;
    }
    interface HTMLNavLinkElement extends Components.NavLink, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNavLinkElement: {
        prototype: HTMLNavLinkElement;
        new (): HTMLNavLinkElement;
    };
    interface HTMLElementTagNameMap {
        "cps-gds-notification-banner": HTMLCpsGdsNotificationBannerElement;
        "cps-global-banner": HTMLCpsGlobalBannerElement;
        "cps-global-case-details": HTMLCpsGlobalCaseDetailsElement;
        "cps-global-case-locking-interstitial": HTMLCpsGlobalCaseLockingInterstitialElement;
        "cps-global-case-locking-notification": HTMLCpsGlobalCaseLockingNotificationElement;
        "cps-global-footer": HTMLCpsGlobalFooterElement;
        "cps-global-footer-content": HTMLCpsGlobalFooterContentElement;
        "cps-global-header": HTMLCpsGlobalHeaderElement;
        "cps-global-home-page-notification": HTMLCpsGlobalHomePageNotificationElement;
        "cps-global-menu": HTMLCpsGlobalMenuElement;
        "cps-global-notifications": HTMLCpsGlobalNotificationsElement;
        "cps-global-recent-cases": HTMLCpsGlobalRecentCasesElement;
        "cps-region": HTMLCpsRegionElement;
        "cps-skip-link": HTMLCpsSkipLinkElement;
        "cps-skip-links": HTMLCpsSkipLinksElement;
        "nav-link": HTMLNavLinkElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface CpsGdsNotificationBanner {
        /**
          * Show only the header until the user asks for detail — the prototype's progressive enhancement, reimplemented rather than bolted on with jQuery. The toggle carries aria-expanded and aria-controls, and the content is genuinely `hidden` when collapsed, so assistive tech is told the same story the sighted user gets rather than reading content that looks closed.
          * @default false
         */
        "collapsible"?: boolean;
        /**
          * Prevent the banner from being focused on page load (only relevant for success type).
          * @default false
         */
        "disableAutoFocus"?: boolean;
        /**
          * Renders the dismiss button. Persistence is the caller's responsibility via the `cpsDismissed` event.
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Fired when the user clicks the dismiss button.
         */
        "onCpsDismissed"?: (event: CpsGdsNotificationBannerCustomEvent<void>) => void;
        /**
          * Pin the banner to the bottom of the viewport instead of letting it sit in the document flow. Matches the UCD prototype's app-notification-banner-pinned.
          * @default false
         */
        "pinned"?: boolean;
        /**
          * Override the ARIA role. Defaults to "region" (or "alert" for success type).
         */
        "role"?: string;
        /**
          * The heading level for the title (1-6). Defaults to 2.
          * @default 2
         */
        "titleHeadingLevel"?: number;
        /**
          * Custom id for the title element. Defaults to "govuk-notification-banner-title".
          * @default "govuk-notification-banner-title"
         */
        "titleId"?: string;
        /**
          * The title text shown in the banner header. Defaults to "Important" or "Success" based on type.
         */
        "titleText"?: string;
        /**
          * Set to "success" for the green success variant. Omit for the default (information) variant.
         */
        "type"?: NotificationBannerType;
    }
    interface CpsGlobalBanner {
    }
    interface CpsGlobalCaseDetails {
    }
    /**
     * The interruption, from the UCD prototype's moj-interruption-card.
     * WHY NOT A MODAL <dialog>
     * showModal() is the tidy answer to "block the page accessibly" — the browser
     * inerts the whole document, traps focus and supplies a backdrop, all without
     * touching the host's DOM. But it puts the dialog in the TOP LAYER, which covers
     * everything, and the design keeps the header and footer visible. So we do it
     * ourselves: an overlay occupying the band below the header, plus `inert` on the
     * host's content.
     * WHAT `inert` BUYS
     * Covering the page visually is not enough. Without it a screen reader still
     * reads the case underneath and the keyboard still tabs into it — the user is
     * told to stop while the page quietly says otherwise. `inert` removes those
     * elements from the accessibility tree AND the tab order in one attribute.
     * WE MUTATE HOST DOM HERE, WHICH WE OTHERWISE AVOID. It is confined to setting
     * and clearing `inert` on the direct children of <body>, excluding our own root,
     * and every path that hides the overlay releases it — including
     * disconnectedCallback, because a host app that tears us down mid-interruption
     * must not be left with an unusable page.
     * ACCESSIBILITY
     * role="alertdialog" is the role for an interruption that demands a decision.
     * Focus moves into the card when it appears, so assistive tech announces it
     * rather than leaving it to be discovered, and Escape dismisses — both choices
     * are visible, so trapping the keyboard would cost more than it buys.
     */
    interface CpsGlobalCaseLockingInterstitial {
    }
    interface CpsGlobalCaseLockingNotification {
    }
    interface CpsGlobalFooter {
        "userEmail"?: string;
    }
    interface CpsGlobalFooterContent {
        "userEmail"?: string;
    }
    interface CpsGlobalHeader {
        /**
          * @default false
         */
        "isDcf"?: boolean;
    }
    interface CpsGlobalHomePageNotification {
    }
    interface CpsGlobalMenu {
    }
    interface CpsGlobalNotifications {
    }
    interface CpsGlobalRecentCases {
        /**
          * @default ""
         */
        "itemClass"?: string;
        /**
          * @default "{urn} - {description}"
         */
        "itemTextTemplate"?: string;
        /**
          * @default "govuk-link"
         */
        "linkClass"?: string;
        /**
          * @default "govuk-list govuk-list--spaced govuk-list--bullet"
         */
        "listClass"?: string;
    }
    interface CpsRegion {
        /**
          * Identifier passed to the central service when this region enters or leaves "present" state. Reflected so it's readable as an attribute.
         */
        "code": string;
        /**
          * Optional subject for kinds that are scoped to one — a witness, a defendant. With it the section is "<caseId>:KIND:<subjectId>"; without it the section is case-wide, "<caseId>:KIND". Must match the id the other clients use for the same person, or the two register different sections for one subject.
         */
        "subject"?: string;
    }
    interface CpsSkipLink {
        "targetSelector"?: string;
        /**
          * @default false
         */
        "useScroll"?: boolean;
    }
    interface CpsSkipLinks {
    }
    interface NavLink {
        "ariaSelected"?: boolean;
        "dcfContextsToUseEventNavigation"?: ContextsToUseEventNavigation;
        "disabled"?: boolean;
        "href"?: string;
        "label"?: string;
        "onCps-global-header-event"?: (event: NavLinkCustomEvent<string>) => void;
        "openInNewTab"?: boolean;
        "selected"?: boolean;
    }

    interface CpsGdsNotificationBannerAttributes {
        "type": NotificationBannerType;
        "titleText": string;
        "titleId": string;
        "titleHeadingLevel": number;
        "role": string;
        "disableAutoFocus": boolean;
        "dismissible": boolean;
        "pinned": boolean;
        "collapsible": boolean;
    }
    interface CpsGlobalFooterAttributes {
        "userEmail": string;
    }
    interface CpsGlobalFooterContentAttributes {
        "userEmail": string;
    }
    interface CpsGlobalHeaderAttributes {
        "isDcf": boolean;
    }
    interface CpsGlobalRecentCasesAttributes {
        "listClass": string;
        "itemClass": string;
        "linkClass": string;
        "itemTextTemplate": string;
    }
    interface CpsRegionAttributes {
        "code": string;
        "subject": string;
    }
    interface CpsSkipLinkAttributes {
        "targetSelector": string;
        "useScroll": boolean;
    }
    interface NavLinkAttributes {
        "label": string;
        "href": string;
        "selected": boolean;
        "ariaSelected": boolean;
        "disabled": boolean;
        "openInNewTab": boolean;
    }

    interface IntrinsicElements {
        "cps-gds-notification-banner": Omit<CpsGdsNotificationBanner, keyof CpsGdsNotificationBannerAttributes> & { [K in keyof CpsGdsNotificationBanner & keyof CpsGdsNotificationBannerAttributes]?: CpsGdsNotificationBanner[K] } & { [K in keyof CpsGdsNotificationBanner & keyof CpsGdsNotificationBannerAttributes as `attr:${K}`]?: CpsGdsNotificationBannerAttributes[K] } & { [K in keyof CpsGdsNotificationBanner & keyof CpsGdsNotificationBannerAttributes as `prop:${K}`]?: CpsGdsNotificationBanner[K] };
        "cps-global-banner": CpsGlobalBanner;
        "cps-global-case-details": CpsGlobalCaseDetails;
        "cps-global-case-locking-interstitial": CpsGlobalCaseLockingInterstitial;
        "cps-global-case-locking-notification": CpsGlobalCaseLockingNotification;
        "cps-global-footer": Omit<CpsGlobalFooter, keyof CpsGlobalFooterAttributes> & { [K in keyof CpsGlobalFooter & keyof CpsGlobalFooterAttributes]?: CpsGlobalFooter[K] } & { [K in keyof CpsGlobalFooter & keyof CpsGlobalFooterAttributes as `attr:${K}`]?: CpsGlobalFooterAttributes[K] } & { [K in keyof CpsGlobalFooter & keyof CpsGlobalFooterAttributes as `prop:${K}`]?: CpsGlobalFooter[K] };
        "cps-global-footer-content": Omit<CpsGlobalFooterContent, keyof CpsGlobalFooterContentAttributes> & { [K in keyof CpsGlobalFooterContent & keyof CpsGlobalFooterContentAttributes]?: CpsGlobalFooterContent[K] } & { [K in keyof CpsGlobalFooterContent & keyof CpsGlobalFooterContentAttributes as `attr:${K}`]?: CpsGlobalFooterContentAttributes[K] } & { [K in keyof CpsGlobalFooterContent & keyof CpsGlobalFooterContentAttributes as `prop:${K}`]?: CpsGlobalFooterContent[K] };
        "cps-global-header": Omit<CpsGlobalHeader, keyof CpsGlobalHeaderAttributes> & { [K in keyof CpsGlobalHeader & keyof CpsGlobalHeaderAttributes]?: CpsGlobalHeader[K] } & { [K in keyof CpsGlobalHeader & keyof CpsGlobalHeaderAttributes as `attr:${K}`]?: CpsGlobalHeaderAttributes[K] } & { [K in keyof CpsGlobalHeader & keyof CpsGlobalHeaderAttributes as `prop:${K}`]?: CpsGlobalHeader[K] };
        "cps-global-home-page-notification": CpsGlobalHomePageNotification;
        "cps-global-menu": CpsGlobalMenu;
        "cps-global-notifications": CpsGlobalNotifications;
        "cps-global-recent-cases": Omit<CpsGlobalRecentCases, keyof CpsGlobalRecentCasesAttributes> & { [K in keyof CpsGlobalRecentCases & keyof CpsGlobalRecentCasesAttributes]?: CpsGlobalRecentCases[K] } & { [K in keyof CpsGlobalRecentCases & keyof CpsGlobalRecentCasesAttributes as `attr:${K}`]?: CpsGlobalRecentCasesAttributes[K] } & { [K in keyof CpsGlobalRecentCases & keyof CpsGlobalRecentCasesAttributes as `prop:${K}`]?: CpsGlobalRecentCases[K] };
        "cps-region": Omit<CpsRegion, keyof CpsRegionAttributes> & { [K in keyof CpsRegion & keyof CpsRegionAttributes]?: CpsRegion[K] } & { [K in keyof CpsRegion & keyof CpsRegionAttributes as `attr:${K}`]?: CpsRegionAttributes[K] } & { [K in keyof CpsRegion & keyof CpsRegionAttributes as `prop:${K}`]?: CpsRegion[K] } & OneOf<"code", CpsRegion["code"], CpsRegionAttributes["code"]>;
        "cps-skip-link": Omit<CpsSkipLink, keyof CpsSkipLinkAttributes> & { [K in keyof CpsSkipLink & keyof CpsSkipLinkAttributes]?: CpsSkipLink[K] } & { [K in keyof CpsSkipLink & keyof CpsSkipLinkAttributes as `attr:${K}`]?: CpsSkipLinkAttributes[K] } & { [K in keyof CpsSkipLink & keyof CpsSkipLinkAttributes as `prop:${K}`]?: CpsSkipLink[K] };
        "cps-skip-links": CpsSkipLinks;
        "nav-link": Omit<NavLink, keyof NavLinkAttributes> & { [K in keyof NavLink & keyof NavLinkAttributes]?: NavLink[K] } & { [K in keyof NavLink & keyof NavLinkAttributes as `attr:${K}`]?: NavLinkAttributes[K] } & { [K in keyof NavLink & keyof NavLinkAttributes as `prop:${K}`]?: NavLink[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cps-gds-notification-banner": LocalJSX.IntrinsicElements["cps-gds-notification-banner"] & JSXBase.HTMLAttributes<HTMLCpsGdsNotificationBannerElement>;
            "cps-global-banner": LocalJSX.IntrinsicElements["cps-global-banner"] & JSXBase.HTMLAttributes<HTMLCpsGlobalBannerElement>;
            "cps-global-case-details": LocalJSX.IntrinsicElements["cps-global-case-details"] & JSXBase.HTMLAttributes<HTMLCpsGlobalCaseDetailsElement>;
            /**
             * The interruption, from the UCD prototype's moj-interruption-card.
             * WHY NOT A MODAL <dialog>
             * showModal() is the tidy answer to "block the page accessibly" — the browser
             * inerts the whole document, traps focus and supplies a backdrop, all without
             * touching the host's DOM. But it puts the dialog in the TOP LAYER, which covers
             * everything, and the design keeps the header and footer visible. So we do it
             * ourselves: an overlay occupying the band below the header, plus `inert` on the
             * host's content.
             * WHAT `inert` BUYS
             * Covering the page visually is not enough. Without it a screen reader still
             * reads the case underneath and the keyboard still tabs into it — the user is
             * told to stop while the page quietly says otherwise. `inert` removes those
             * elements from the accessibility tree AND the tab order in one attribute.
             * WE MUTATE HOST DOM HERE, WHICH WE OTHERWISE AVOID. It is confined to setting
             * and clearing `inert` on the direct children of <body>, excluding our own root,
             * and every path that hides the overlay releases it — including
             * disconnectedCallback, because a host app that tears us down mid-interruption
             * must not be left with an unusable page.
             * ACCESSIBILITY
             * role="alertdialog" is the role for an interruption that demands a decision.
             * Focus moves into the card when it appears, so assistive tech announces it
             * rather than leaving it to be discovered, and Escape dismisses — both choices
             * are visible, so trapping the keyboard would cost more than it buys.
             */
            "cps-global-case-locking-interstitial": LocalJSX.IntrinsicElements["cps-global-case-locking-interstitial"] & JSXBase.HTMLAttributes<HTMLCpsGlobalCaseLockingInterstitialElement>;
            "cps-global-case-locking-notification": LocalJSX.IntrinsicElements["cps-global-case-locking-notification"] & JSXBase.HTMLAttributes<HTMLCpsGlobalCaseLockingNotificationElement>;
            "cps-global-footer": LocalJSX.IntrinsicElements["cps-global-footer"] & JSXBase.HTMLAttributes<HTMLCpsGlobalFooterElement>;
            "cps-global-footer-content": LocalJSX.IntrinsicElements["cps-global-footer-content"] & JSXBase.HTMLAttributes<HTMLCpsGlobalFooterContentElement>;
            "cps-global-header": LocalJSX.IntrinsicElements["cps-global-header"] & JSXBase.HTMLAttributes<HTMLCpsGlobalHeaderElement>;
            "cps-global-home-page-notification": LocalJSX.IntrinsicElements["cps-global-home-page-notification"] & JSXBase.HTMLAttributes<HTMLCpsGlobalHomePageNotificationElement>;
            "cps-global-menu": LocalJSX.IntrinsicElements["cps-global-menu"] & JSXBase.HTMLAttributes<HTMLCpsGlobalMenuElement>;
            "cps-global-notifications": LocalJSX.IntrinsicElements["cps-global-notifications"] & JSXBase.HTMLAttributes<HTMLCpsGlobalNotificationsElement>;
            "cps-global-recent-cases": LocalJSX.IntrinsicElements["cps-global-recent-cases"] & JSXBase.HTMLAttributes<HTMLCpsGlobalRecentCasesElement>;
            "cps-region": LocalJSX.IntrinsicElements["cps-region"] & JSXBase.HTMLAttributes<HTMLCpsRegionElement>;
            "cps-skip-link": LocalJSX.IntrinsicElements["cps-skip-link"] & JSXBase.HTMLAttributes<HTMLCpsSkipLinkElement>;
            "cps-skip-links": LocalJSX.IntrinsicElements["cps-skip-links"] & JSXBase.HTMLAttributes<HTMLCpsSkipLinksElement>;
            "nav-link": LocalJSX.IntrinsicElements["nav-link"] & JSXBase.HTMLAttributes<HTMLNavLinkElement>;
        }
    }
}
