packages:
  - packages/*
  - apps/*
  - e2e
  - infra/proxy
overrides:
  tar-fs@>=3.0.0 <3.0.9: ">=3.0.9"
  form-data@>=4.0.0 <4.0.4: ">=4.0.4"
  brace-expansion@>=1.0.0 <1.1.12: ">=1.1.12"
  brace-expansion@>=2.0.0 <2.0.2: ">=2.0.2"
  brace-expansion@>=3.0.0 <3.0.1: ">=3.0.1"
  brace-expansion@>=4.0.0 <4.0.1: ">=4.0.1"
  axios@>=1.0.0 <1.12.0: ">=1.12.0 "
