import type { Config } from "../Config";
import { isOutSystemsUrl } from "../is-outsystems-host";

/**
 * Works out which URLs the live checker should probe.
 *
 * Derived rather than hand-listed, because the hand-listed version was wrong in
 * three ways at once: it named three subdomains when the configs reference
 * four, it missed hosts, and it pointed at `/Casework_blocks` after that module
 * had been renamed.
 *
 * `LINKS[].href` is the source of truth for screens. It holds real absolute
 * URLs rather than the regexes in `CONTEXTS[].path`, and it cannot rot quietly
 * — a wrong href breaks the menu in front of users. Which of them are
 * OutSystems is the shared isOutSystemsUrl check, narrowed to the tenants
 * themselves (see servesItsOwnCsp).
 */

export type CheckTarget = {
  environment: string;
  url: string;
  kind: "screen" | "auth-handover";
};

type TargetConfig = Pick<Config, "LINKS" | "OS_HANDOVER_URL">;

// The oapps hosts are CPS reverse proxies in front of the OutSystems tenants.
// The CSP is generated by the OutSystems app, so probing through the proxy would
// re-check the same policy under another name -- and a gap found there would be
// fixed in the app, not the proxy. Only the tenants are probed until oapps owns
// a policy of its own.
const servesItsOwnCsp = (href: string): boolean =>
  isOutSystemsUrl(href) && new URL(href).hostname.endsWith(".outsystemsenterprise.com");

// One probe per app module, not per link. Several links point into the same
// module and OutSystems serves one policy per app, so probing each link would
// multiply the report without adding information.
const moduleRootOf = (href: string): string => {
  const url = new URL(href);
  const firstSegment = url.pathname.split("/").find(Boolean);
  return `${url.origin}/${firstSegment ?? ""}`;
};

export const deriveCheckTargets = (
  environment: string,
  config: TargetConfig,
): CheckTarget[] => {
  const screenRoots = new Set(
    (config.LINKS ?? [])
      .map(link => link.href)
      .filter(servesItsOwnCsp)
      .map(moduleRootOf),
  );

  // The handover page is a distinct check: besides the host's headers, the
  // deployed file itself is compared with this repository's copy.
  const handoverUrl =
    config.OS_HANDOVER_URL && servesItsOwnCsp(config.OS_HANDOVER_URL)
      ? new URL(config.OS_HANDOVER_URL).href
      : undefined;

  return [
    ...[...screenRoots].map(
      (url): CheckTarget => ({ environment, url, kind: "screen" }),
    ),
    ...(handoverUrl
      ? [{ environment, url: handoverUrl, kind: "auth-handover" as const }]
      : []),
  ];
};

export const deriveAllCheckTargets = (
  configsByEnvironment: Record<string, TargetConfig>,
): CheckTarget[] =>
  Object.entries(configsByEnvironment).flatMap(([environment, config]) =>
    deriveCheckTargets(environment, config),
  );
