import {
  deriveCspRequirements,
  formatCspPolicy,
  groupByDirective,
  type CspRelevantConfig,
} from "./derive-csp";
import type { CspRequirement } from "./csp-requirements";

/**
 * Renders the published CSP artifacts.
 *
 * Separate from the script that writes them so a test can assert the committed
 * files still match a fresh render. That check is the whole point: a generated
 * file nobody verifies is indistinguishable from a hand-maintained one, which
 * is how outsystems-support/csp.json spent six months missing
 * graph.microsoft.com while looking authoritative.
 */

// config.accessibility.json is excluded deliberately — the standalone
// blob-hosted demo site, not an OutSystems tenant. Kept identical to the lists
// in derive-csp.spec.ts.
export const CSP_ENVIRONMENTS = ["dev", "test", "uat", "prod"];

export const GENERATED_BANNER =
  "<!-- GENERATED by `pnpm --filter cps-global-configuration generate:csp` — do not edit by hand. -->";

const renderTable = (requirements: CspRequirement[]): string =>
  [
    "| Directive | Source | Why |",
    "| --- | --- | --- |",
    ...requirements.map(
      r => `| \`${r.directive}\` | \`${r.value}\` | ${r.reason} |`,
    ),
  ].join("\n");

type EnvironmentRequirements = {
  env: string;
  requirements: CspRequirement[];
  handoverRequirements: CspRequirement[];
};

const renderPolicySection = (requirements: CspRequirement[]): string[] => [
  renderTable(requirements),
  "",
  "```",
  formatCspPolicy(requirements),
  "```",
  "",
];

const renderMarkdown = (perEnvironment: EnvironmentRequirements[]): string =>
  [
    GENERATED_BANNER,
    "",
    "# Content Security Policy requirements",
    "",
    "What an OutSystems host application must allow for the global components to",
    "work. Derived from `configuration/config.<env>.json`, so it cannot drift from",
    "the endpoints it describes — move an endpoint and this moves with it.",
    "",
    "> **This is a snapshot of what we require, not evidence that any host allows",
    "> it.** For what the OutSystems apps are actually serving right now, run",
    "> `pnpm --filter cps-global-configuration check:csp`.",
    "",
    "Regenerate with `pnpm --filter cps-global-configuration generate:csp`.",
    "",
    ...perEnvironment.flatMap(({ env, requirements, handoverRequirements }) => [
      `## \`${env}\``,
      "",
      ...renderPolicySection(requirements),
      `### \`${env}\`: \`/Casework_Patterns/auth-handover.html\``,
      "",
      "The handover page carries no CSP of its own. If the host serves one on",
      "this page, it must allow the following -- including the keyword sources the",
      "page's inline bootstrap script and same-origin fetches need.",
      "",
      ...renderPolicySection(handoverRequirements),
    ]),
  ].join("\n");

const asJson = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

/**
 * Returns every published artifact keyed by filename, so callers can write them
 * or compare them without knowing the set in advance.
 */
export const buildCspArtifacts = (
  configsByEnvironment: Record<string, CspRelevantConfig>,
): Record<string, string> => {
  const perEnvironment: EnvironmentRequirements[] = CSP_ENVIRONMENTS.map(env => {
    const { hostApp, handoverPage } = deriveCspRequirements(configsByEnvironment[env]!);
    return { env, requirements: hostApp, handoverRequirements: handoverPage };
  });

  return {
    ...Object.fromEntries(
      perEnvironment.map(({ env, requirements, handoverRequirements }) => [
        `csp.${env}.json`,
        asJson({
          environment: env,
          directives: groupByDirective(requirements),
          policy: formatCspPolicy(requirements),
          requirements,
          authHandover: {
            directives: groupByDirective(handoverRequirements),
            policy: formatCspPolicy(handoverRequirements),
            requirements: handoverRequirements,
          },
        }),
      ]),
    ),
    "CSP-REQUIREMENTS.md": renderMarkdown(perEnvironment),
  };
};
