import {
  deriveCspRequirements,
  deriveHandoverPagePolicy,
  formatCspPolicy,
  groupByDirective,
  type CspRelevantConfig,
} from "./derive-csp";
import type { CspRequirement } from "./csp-requirements";

/**
 * Renders the published CSP artifacts.
 *
 * Separate from the script that writes them so a test can assert the committed
 * files still match a fresh render. That check is the whole point: a generated
 * file nobody verifies is indistinguishable from a hand-maintained one, which
 * is how outsystems-support/csp.json spent six months missing
 * graph.microsoft.com while looking authoritative.
 */

// config.accessibility.json is excluded deliberately — the standalone
// blob-hosted demo site, not an OutSystems tenant. Kept identical to the lists
// in derive-csp.spec.ts and auth-handover-csp.spec.ts.
export const CSP_ENVIRONMENTS = ["dev", "test", "uat", "prod"];

export const GENERATED_BANNER =
  "<!-- GENERATED by `pnpm --filter cps-global-configuration generate:csp` — do not edit by hand. -->";

const renderTable = (requirements: CspRequirement[]): string =>
  [
    "| Directive | Source | Why |",
    "| --- | --- | --- |",
    ...requirements.map(
      r => `| \`${r.directive}\` | \`${r.value}\` | ${r.reason} |`,
    ),
  ].join("\n");

const renderMarkdown = (
  perEnvironment: { env: string; requirements: CspRequirement[] }[],
  handoverPolicy: CspRequirement[],
): string =>
  [
    GENERATED_BANNER,
    "",
    "# Content Security Policy requirements",
    "",
    "What an OutSystems host application must allow for the global components to",
    "work. Derived from `configuration/config.<env>.json`, so it cannot drift from",
    "the endpoints it describes — move an endpoint and this moves with it.",
    "",
    "> **This is a snapshot of what we require, not evidence that any host allows",
    "> it.** For what the OutSystems apps are actually serving right now, run",
    "> `pnpm --filter cps-global-configuration check:csp`.",
    "",
    "Regenerate with `pnpm --filter cps-global-configuration generate:csp`.",
    "",
    ...perEnvironment.flatMap(({ env, requirements }) => [
      `## \`${env}\``,
      "",
      renderTable(requirements),
      "",
      "```",
      formatCspPolicy(requirements),
      "```",
      "",
    ]),
    "## `auth-handover.html`",
    "",
    "The complete meta CSP for the handover page. Unioned across every",
    "environment rather than generated per-environment, because that one file is",
    "uploaded to all the OutSystems tenants by hand and a single file that works",
    "wherever it lands beats four variants someone has to match up correctly.",
    "",
    "Asserted against the shipped file by",
    "`packages/cps-global-handover/src/auth-handover-csp.spec.ts`.",
    "",
    renderTable(handoverPolicy),
    "",
    "```",
    formatCspPolicy(handoverPolicy),
    "```",
    "",
  ].join("\n");

const asJson = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

/**
 * Returns every published artifact keyed by filename, so callers can write them
 * or compare them without knowing the set in advance.
 */
export const buildCspArtifacts = (
  configsByEnvironment: Record<string, CspRelevantConfig>,
): Record<string, string> => {
  const perEnvironment = CSP_ENVIRONMENTS.map(env => ({
    env,
    requirements: deriveCspRequirements(configsByEnvironment[env]!).hostApp,
  }));

  const handoverPolicy = deriveHandoverPagePolicy(
    CSP_ENVIRONMENTS.map(env => configsByEnvironment[env]!),
  );

  return {
    ...Object.fromEntries(
      perEnvironment.map(({ env, requirements }) => [
        `csp.${env}.json`,
        asJson({
          environment: env,
          directives: groupByDirective(requirements),
          policy: formatCspPolicy(requirements),
          requirements,
        }),
      ]),
    ),
    "csp.auth-handover.json": asJson({
      target: "auth-handover.html",
      directives: groupByDirective(handoverPolicy),
      policy: formatCspPolicy(handoverPolicy),
      requirements: handoverPolicy,
    }),
    "CSP-REQUIREMENTS.md": renderMarkdown(perEnvironment, handoverPolicy),
  };
};
