const KEYS_TO_RESET = [
  "$OS_Users$WorkManagementApp$ClientVars$ChosenAreaAPI",
  "$OS_Users$WorkManagementApp$ClientVars$ChosenCourtAPI",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_Court",
  "$OS_Users$WorkManagementApp$ClientVars$ChosenOwnerAPI",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_TaskType",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_Unit",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_URN",
  "$OS_Users$WorkManagementApp$ClientVars$ViewState",
  "$OS_Users$WorkManagementApp$ClientVars$AlertSuccessText",
  "$OS_Users$WorkManagementApp$ClientVars$showAlertSuccess",
  "$OS_Users$WorkManagementApp$ClientVars$AlertWarningText",
  "$OS_Users$WorkManagementApp$ClientVars$showAlertWarning",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_Unit",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_Area2",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_Owner",
  "$OS_Users$WorkManagementApp$ClientVars$AlertSuccessTextAdditional",
  "$OS_Users$WorkManagementApp$ClientVars$CaseFilters_HearingDate",
  "$OS_Users$WorkManagementApp$ClientVars$CaseFilters_HearingDays",
  "$OS_Users$WorkManagementApp$ClientVars$CaseFilters_URN",
  "$OS_Users$WorkManagementApp$ClientVars$CaseFilters_HearingTypeCode",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_HearingDays",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_HearingDate",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_URN",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_Owner",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_UnitGroup",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_FilterTagSetId",
  "$OS_Users$WorkManagementApp$ClientVars$CaseFilters_FilterTagSetId",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_FilterTagSetId",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_OwnerDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_AdditionalOwners",
  "$OS_Users$WorkManagementApp$ClientVars$TaskFilters_UnitDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$PriorityChargingFilters_AreaDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_Areas",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_Assignees",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_Caseworkers",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_DateDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_EndDate",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_Prosecutors",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_StartDate",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_Units",
  "$OS_Users$WorkManagementApp$ClientVars$Directions_URN",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_AdditionalOwners",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_CPSAreaDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_CPSAreaId",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_FilterTagSetId",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_Owner",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_OwnerDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_Unit",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_UnitDisplay",
  "$OS_Users$WorkManagementApp$ClientVars$TriageFilters_URN",
];

export const resetTasklistFilters = ({ localStorage }: Window) => {
  try {
    KEYS_TO_RESET.forEach((key) => localStorage.removeItem(key));
  } catch (error) {
    console.error(`resetTasklistFilters error: ${error}`);
  }
};
