/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LinkProps } from "./components/cps-global-header/internal/LinkProps";
export { LinkProps } from "./components/cps-global-header/internal/LinkProps";
export namespace Components {
    interface CpsGlobalHeader {
        /**
          * The text to appear at the start of the second row
         */
        "name": string;
    }
    interface CpsGlobalHeaderExperimental {
        "forceEnvironment": string;
        /**
          * The text to appear at the start of the second row
         */
        "name": string;
    }
    interface DropDown {
        "label": string;
        "links": LinkProps[];
        "menuAlignment": "left" | "right";
    }
    interface NavLink {
        "disabled": boolean;
        "href": string;
        "label": string;
        "openInNewTab"?: boolean;
        "selected": boolean;
    }
}
export interface CpsGlobalHeaderExperimentalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCpsGlobalHeaderExperimentalElement;
}
export interface NavLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNavLinkElement;
}
declare global {
    interface HTMLCpsGlobalHeaderElement extends Components.CpsGlobalHeader, HTMLStencilElement {
    }
    var HTMLCpsGlobalHeaderElement: {
        prototype: HTMLCpsGlobalHeaderElement;
        new (): HTMLCpsGlobalHeaderElement;
    };
    interface HTMLCpsGlobalHeaderExperimentalElementEventMap {
        "cpsGlobalNavEvent": string;
    }
    interface HTMLCpsGlobalHeaderExperimentalElement extends Components.CpsGlobalHeaderExperimental, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCpsGlobalHeaderExperimentalElementEventMap>(type: K, listener: (this: HTMLCpsGlobalHeaderExperimentalElement, ev: CpsGlobalHeaderExperimentalCustomEvent<HTMLCpsGlobalHeaderExperimentalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCpsGlobalHeaderExperimentalElementEventMap>(type: K, listener: (this: HTMLCpsGlobalHeaderExperimentalElement, ev: CpsGlobalHeaderExperimentalCustomEvent<HTMLCpsGlobalHeaderExperimentalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCpsGlobalHeaderExperimentalElement: {
        prototype: HTMLCpsGlobalHeaderExperimentalElement;
        new (): HTMLCpsGlobalHeaderExperimentalElement;
    };
    interface HTMLDropDownElement extends Components.DropDown, HTMLStencilElement {
    }
    var HTMLDropDownElement: {
        prototype: HTMLDropDownElement;
        new (): HTMLDropDownElement;
    };
    interface HTMLNavLinkElementEventMap {
        "cps-global-header-event": string;
    }
    interface HTMLNavLinkElement extends Components.NavLink, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNavLinkElementEventMap>(type: K, listener: (this: HTMLNavLinkElement, ev: NavLinkCustomEvent<HTMLNavLinkElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNavLinkElement: {
        prototype: HTMLNavLinkElement;
        new (): HTMLNavLinkElement;
    };
    interface HTMLElementTagNameMap {
        "cps-global-header": HTMLCpsGlobalHeaderElement;
        "cps-global-header-experimental": HTMLCpsGlobalHeaderExperimentalElement;
        "drop-down": HTMLDropDownElement;
        "nav-link": HTMLNavLinkElement;
    }
}
declare namespace LocalJSX {
    interface CpsGlobalHeader {
        /**
          * The text to appear at the start of the second row
         */
        "name"?: string;
    }
    interface CpsGlobalHeaderExperimental {
        "forceEnvironment"?: string;
        /**
          * The text to appear at the start of the second row
         */
        "name"?: string;
        "onCpsGlobalNavEvent"?: (event: CpsGlobalHeaderExperimentalCustomEvent<string>) => void;
    }
    interface DropDown {
        "label"?: string;
        "links"?: LinkProps[];
        "menuAlignment"?: "left" | "right";
    }
    interface NavLink {
        "disabled"?: boolean;
        "href"?: string;
        "label"?: string;
        "onCps-global-header-event"?: (event: NavLinkCustomEvent<string>) => void;
        "openInNewTab"?: boolean;
        "selected"?: boolean;
    }
    interface IntrinsicElements {
        "cps-global-header": CpsGlobalHeader;
        "cps-global-header-experimental": CpsGlobalHeaderExperimental;
        "drop-down": DropDown;
        "nav-link": NavLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cps-global-header": LocalJSX.CpsGlobalHeader & JSXBase.HTMLAttributes<HTMLCpsGlobalHeaderElement>;
            "cps-global-header-experimental": LocalJSX.CpsGlobalHeaderExperimental & JSXBase.HTMLAttributes<HTMLCpsGlobalHeaderExperimentalElement>;
            "drop-down": LocalJSX.DropDown & JSXBase.HTMLAttributes<HTMLDropDownElement>;
            "nav-link": LocalJSX.NavLink & JSXBase.HTMLAttributes<HTMLNavLinkElement>;
        }
    }
}
