#!/usr/bin/env bash
#
# build.sh — concatenate the presence bundle the app maintainers inject.
#
# Two variants, both emitting ../cms-presence-client.js (the deployed path, so
# nginx and the deploy script never change):
#
#   ./build.sh           JSONP client — cms-presence-client.src.js alone. No
#                        vendor, no Promise polyfill, no globals patched onto the
#                        host page. This is what ships.
#
#   ./build.sh signalr   SignalR client — vendor/es6-promise + vendor/signalr 3.1
#                        + cms-presence-client.signalr.src.js. Kept as a reference;
#                        see that file's header for why it is not the shipping one.
#
# Plain concatenation, deliberately: every input is already ES5, so there is
# nothing to transpile and no bundler to go wrong. Both vendor files are UMD
# and self-register on window (Promise polyfill auto-installs; signalR attaches
# window.signalR), which is exactly what the glue expects.
#
# No token substitution: the client ships no credential. The proxy injects
# Authorization from the HttpOnly presence cookie (see presenceBearer).
#
# Usage:  ./build.sh          (then deploy — see README.md)
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/../cms-presence-client.js"
VARIANT="${1:-jsonp}"

if [ "$VARIANT" = "signalr" ]; then
  SRC="$DIR/cms-presence-client.signalr.src.js"
  [ -f "$SRC" ] || { echo "Missing $SRC" >&2; exit 1; }
  {
    echo "/* cms-presence-client.js — GENERATED by cms-presence-client/build.sh signalr."
    echo " * DO NOT EDIT. Reference SignalR variant; see cms-presence-client.signalr.src.js."
    echo " */"
    echo
    echo "/* ---- 1. es6-promise 4.2.8 (MIT) ---- */"
    cat "$DIR/vendor/es6-promise-4.2.8.auto.min.js"
    echo
    echo "/* ---- 2. @microsoft/signalr 3.1.31 (Apache-2.0) ---- */"
    cat "$DIR/vendor/signalr-3.1.31.min.js"
    echo
    echo "/* ---- 3. presence glue ---- */"
    cat "$SRC"
  } > "$OUT"
  echo "built $OUT (signalr variant, $(wc -c < "$OUT" | tr -d ' ') bytes)"
  grep -q "__DEV_BEARER__\|eyJ0eXAiOiJKV1Qi" "$OUT" && { echo "ERROR: a credential leaked into the bundle" >&2; exit 1; }
  echo "no credential in bundle OK"
  exit 0
fi

{
  echo "/* cms-presence-client.js — GENERATED by cms-presence-client/build.sh. DO NOT EDIT."
  echo " *"
  echo " * Presence client for CMS Modern (/viewer/) and DCF (/dcf/), both of which run"
  echo " * in Edge IE mode at document mode 11. JSONP transport — no vendor code, no"
  echo " * Promise polyfill, nothing patched onto the host page."
  echo " *"
  echo " * Edit cms-presence-client/cms-presence-client.src.js and re-run build.sh."
  echo " */"
  echo
  cat "$DIR/cms-presence-client.src.js"
} > "$OUT"

echo "built $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
grep -q "__DEV_BEARER__\|eyJ0eXAiOiJKV1Qi" "$OUT" && { echo "ERROR: a credential leaked into the bundle" >&2; exit 1; }
echo "no credential in bundle OK"
