#!/usr/bin/env bash
#
# build.sh — concatenate the presence bundle the app maintainers inject.
#
#   vendor/es6-promise-4.2.8.auto.min.js   IE11 has no native Promise
#   vendor/signalr-3.1.31.min.js           last SignalR line supporting IE11
#   cms-presence-client.src.js             our glue
#     -> ../cms-presence-client.js         the single deployed script
#
# Plain concatenation, deliberately: every input is already ES5, so there is
# nothing to transpile and no bundler to go wrong. Both vendor files are UMD
# and self-register on window (Promise polyfill auto-installs; signalR attaches
# window.signalR), which is exactly what the glue expects.
#
# No token substitution: the client ships no credential. The proxy injects
# Authorization from the HttpOnly presence cookie (see presenceBearer).
#
# Usage:  ./build.sh          (then deploy — see README.md)
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/../cms-presence-client.js"
{
  echo "/* cms-presence-client.js — GENERATED by cms-presence-client/build.sh. DO NOT EDIT."
  echo " *"
  echo " * Presence POC for CMS Modern (/viewer/) and DCF (/dcf/), both of which run in"
  echo " * Edge IE mode at document mode 11. Bundle contents, in order:"
  echo " *   1. es6-promise 4.2.8   (Promise polyfill — IE11 has none)"
  echo " *   2. @microsoft/signalr 3.1.31  (last line supporting IE11; v8 is ES2015+)"
  echo " *   3. cms-presence-client.src.js (the hand-written glue)"
  echo " *"
  echo " * Edit cms-presence-client/cms-presence-client.src.js and re-run build.sh."
  echo " */"
  echo
  echo "/* ---- 1. es6-promise 4.2.8 (MIT) ---- */"
  cat "$DIR/vendor/es6-promise-4.2.8.auto.min.js"
  echo
  echo "/* ---- 2. @microsoft/signalr 3.1.31 (Apache-2.0) ---- */"
  cat "$DIR/vendor/signalr-3.1.31.min.js"
  echo
  echo "/* ---- 3. presence glue ---- */"
  cat "$DIR/cms-presence-client.src.js"
} > "$OUT"

echo "built $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
grep -q "__DEV_BEARER__\|eyJ0eXAiOiJKV1Qi" "$OUT" && { echo "ERROR: a credential leaked into the bundle" >&2; exit 1; }
echo "no credential in bundle OK"
