js_import glocovnext from templates/global-components.vnext.js;

# Environment variables passed to njs (used by the swagger body filter)
js_var $wm_mds_base_url ${WM_MDS_BASE_URL};

# Utility to let us know if we are healthy or not
location = /global-components/status {
  js_content glocovnext.handleStatus;
}
# Handle swagger for MDS specially to filter the body
location ~ ^/global-components/(.*swagger(\.json|/ui).*)$ {
  error_page 418 = @gloco_preflight;
  if ($request_method = OPTIONS) {
    return 418;
  }

  proxy_hide_header Access-Control-Allow-Origin;
  proxy_hide_header Access-Control-Allow-Credentials;

  add_header Access-Control-Allow-Origin $cors_origin always;
  add_header Access-Control-Allow-Credentials true always;

  proxy_set_header x-functions-key "${WM_MDS_ACCESS_KEY}";
  proxy_set_header Accept-Encoding "";  # Disable compression for body filter
  proxy_pass ${WM_MDS_BASE_URL}$1;

  js_body_filter glocovnext.filterSwaggerBody buffer_type=string;
}

# Allows other calls to validate Bearer token. Doesn't support
#  audience/scopes beyond standard MS ones
location = /global-components/validate-token {
    internal;
    resolver ${WEBSITE_DNS_SERVER} ipv6=off valid=30s;
    js_fetch_verify off;
    js_content glocovnext.handleValidateToken;
}

