GloCo__UserAreaMapping
| project Auth_Username, Area = User_AreaOrCPSD
| join kind=inner  
    (GloCo_PageViews_CaseReview | project TimeGenerated, CaseId, Auth_Username | where TimeGenerated > datetime(2026-03-09T12:00:01))
    on Auth_Username 
| project-away Auth_Username1
| distinct CaseId, Area, Week = format_datetime(startofweek(TimeGenerated), "yyyy-MM-dd")
| summarize CountCasesReviewed = count() by Area, Week
| as T
| union (T | summarize CountCasesReviewed = sum(CountCasesReviewed) by Area | extend Week = "Total")
| evaluate pivot(Week, sum(CountCasesReviewed), Area)
| order by Area asc
