js_import glococms from templates/global-components.navigate-cms.js;

# Single entry point. Use ?step=close to indicate the close phase.
location = /global-components/navigate-cms {
  js_content glococms.handleNavigateCms;
}
