name: CI-CD, Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  BUILD_PATH: "./packages/cps-global-components/dist/cps-global-components.*"
  BUILD_ARTIFACT_NAME: build-artifact
  DEPLOY_ENVIRONMENT: ci-cd-test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cps-global-components
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      # - run: pnpm run lint
      #   continue-on-error: false

      - run: pnpm test
        env:
          CI: true

      # - run: pnpm run test:coverage
      #   continue-on-error: true

      - run: pnpm run build

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{env.BUILD_ARTIFACT_NAME}}
          path: ${{ env.BUILD_PATH }}
          retention-days: 1

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        id: download
        with:
          artifact-ids: ${{needs.build-and-test.outputs.artifact-id}}

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage container create \
              --name $DEPLOY_ENVIRONMENT \
              --public-access container \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --destination $DEPLOY_ENVIRONMENT \
              --source "${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"
              --overwrite

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm audit --audit-level high

      - uses: actions/dependency-review-action@v4
