name: CI-CD, Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  BUILD_ARTIFACT_NAME: build-artifact

jobs:
  generate-matrix:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/shared/generate-matrix.yml

  build-and-test:
    uses: ./.github/workflows/shared/build-and-test.yml

  deploy-script:
    needs: [generate-matrix, build-and-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}
    uses: ./.github/workflows/shared/deploy-script.yml
    with:
      environment: ${{ matrix.environment }}
      artifact-id: ${{ needs.build-and-test.outputs.artifact-id }}
    secrets:
      BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}

  deploy-harnesses:
    needs: generate-matrix
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}
    uses: ./.github/workflows/shared/deploy-harnesses.yml
    with:
      environment: ${{ matrix.environment }}
    secrets:
      BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}

  deploy-home:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/shared/deploy-home.yml
    secrets:
      BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}

  repo-security-scan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared/repo-security-scan.yml

  org-security-scan:
    if: github.event_name == 'pull_request'

    permissions:
      security-events: write
      statuses: write

    uses: CPS-Innovation/.github/.github/workflows/security-scan.yml@main
