name: CI-CD, Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  BUILD_ARTIFACT_NAME: build-artifact

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - uses: actions/checkout@v4

      - name: List files and create JSON matrix
        id: set-environments
        run: |
          files=$(ls ./configuration | grep 'config\.[^\\.]*\.json' | jq -R . | jq -s -c . |  jq 'map(capture("config\\.(?<environment>[A-Za-z0-9_-]+)\\.json") | .environment)' | jq -c .)
          echo "Files found: $files"
          echo "environments=$files" >> "$GITHUB_OUTPUT"

  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install
        env:
          CI: true

      - run: pnpm --filter "./packages/*" build

      # - run: pnpm run lint
      #   continue-on-error: false

      - run: pnpm --filter cps-global-components test

      # - run: pnpm run test:coverage
      #   continue-on-error: true

      - run: pnpm --filter cps-global-configuration validate

      - run: 'pnpm --filter cps-global-components run rollup --intro ''window.cps_global_components_build = {Sha: "${{ steps.short-sha.outputs.sha }}", RunId: "${{ github.run_number }}", Timestamp: "${{ github.event.repository.updated_at }}"};'''

      - run: |
          cp -r ./packages/cps-global-components/dist/cps-global-components.js ./e2e/harness
          pnpm --filter e2e test

      - run: |
          rm -rf ./to-deploy
          mkdir -p ./to-deploy
          cp ./packages/cps-global-components/dist/cps-global-components.js ./to-deploy
          cp ./packages/cps-global-components/dist/cps-global-components.js.map ./to-deploy
          cp ./packages/cps-global-os-handover/dist/auth-handover.js ./to-deploy
          cp ./packages/cps-global-os-handover/dist/auth-handover.js.map ./to-deploy

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{env.BUILD_ARTIFACT_NAME}}
          path: |
            ./to-deploy/*
          retention-days: 1

  deploy-script:
    needs: [generate-matrix, build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - uses: actions/download-artifact@v4
        id: download
        with:
          artifact-ids: ${{needs.build-and-test.outputs.artifact-id}}

      - run: |
          cp ./configuration/config.${{matrix.environment}}.json ${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/config.json
          if [ -f "./configuration/config.${{matrix.environment}}.override.json" ]; then
            cp ./configuration/config.${{matrix.environment}}.override.json ${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/config.override.json

            cp ./configuration/config.${{matrix.environment}}.override.json ${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/config.override.js
            sed -i '1s/^/cps_global_components_config_jsonp_callback(/; $s/$/);/' ${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/config.override.js
          fi

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage container create \
              --name ${{matrix.environment}} \
              --public-access container \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination ${{matrix.environment}} \
              --source "${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}" \
              --overwrite true \
              --content-cache-control "max-age=20, stale-while-revalidate=3600, stale-if-error=3600" \
              --metadata buildsha=${{ steps.short-sha.outputs.sha }} buildrunid=${{ github.run_number }} buildtimestamp="${{ github.event.repository.updated_at }}"

  deploy-harnesses:
    needs: generate-matrix
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          # Extract our account name from the connection string
          ACCOUNT_NAME=$(echo "${{secrets.BLOB_STORAGE_CONNECTION_STRING}}" | grep -oP 'AccountName=\K[^;]+')

          # Both harnesses look to env variables for the location of the global script
          GLOBAL_SCRIPT_URL="https://$ACCOUNT_NAME.blob.core.windows.net/${{matrix.environment}}/cps-global-components.js"
          echo "GLOBAL_SCRIPT_URL=$GLOBAL_SCRIPT_URL" >> $GITHUB_ENV
          echo "VITE_GLOBAL_SCRIPT_URL=$GLOBAL_SCRIPT_URL" >> $GITHUB_ENV

          # The static harness also needs a BASE_PATH for hyperlinks to be consistent
          echo "BASE_PATH=/${{matrix.environment}}/static" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install
        env:
          CI: true

      - run: pnpm --recursive build

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob delete-batch \
                --source '$web' \
                --pattern "${{matrix.environment}}/static/*" \
                --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination "\$web/${{matrix.environment}}/static" \
              --source "./apps/harness-html/_site" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob delete-batch \
                --source '$web' \
                --pattern "${{matrix.environment}}/spa/*" \
                --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination "\$web/${{matrix.environment}}/spa" \
              --source "./apps/harness-spa/dist" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

  deploy-home:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob delete-batch \
                --source '$web' \
                --pattern "home/*" \
                --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination "\$web/home" \
              --source "./apps/home" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

  deploy-auth-handover:
    needs: [generate-matrix, build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          artifact-ids: ${{needs.build-and-test.outputs.artifact-id}}

      - name: Prepare auth-handover script with environment config
        run: |
          # Read config values for the environment
          CONFIG_FILE="./configuration/config.${{matrix.environment}}.json"
          COOKIE_HANDOVER_URL=$(jq -r '.COOKIE_HANDOVER_URL' "$CONFIG_FILE")
          TOKEN_HANDOVER_URL=$(jq -r '.TOKEN_HANDOVER_URL' "$CONFIG_FILE")

          # Create the output directory
          rm -rf ./prepared-auth-handover
          mkdir -p ./prepared-auth-handover

          # Prepend the window variables to the auth-handover.js file
          echo "window.cps_global_components_cookie_handover_url = '$COOKIE_HANDOVER_URL';" > ./prepared-auth-handover/prepared-auth-handover.js
          echo "window.cps_global_components_token_handover_url = '$TOKEN_HANDOVER_URL';" >> ./prepared-auth-handover/prepared-auth-handover.js
          cat "${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/auth-handover.js" >> ./prepared-auth-handover/prepared-auth-handover.js

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload \
              --container-name ${{matrix.environment}} \
              --file "./prepared-auth-handover/prepared-auth-handover.js" \
              --name "auth-handover.js" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}" \
              --overwrite true \
              --content-cache-control "max-age=20, stale-while-revalidate=3600, stale-if-error=3600" \
              --metadata buildsha=${{ steps.short-sha.outputs.sha }} buildrunid=${{ github.run_number }} buildtimestamp="${{ github.event.repository.updated_at }}"

  repo-security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm audit --audit-level high

      - uses: actions/dependency-review-action@v4

  org-security-scan:
    if: github.event_name == 'pull_request'

    permissions:
      security-events: write
      statuses: write

    uses: CPS-Innovation/.github/.github/workflows/security-scan.yml@main
