name: CI-CD, Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  BUILD_ARTIFACT_NAME: build-artifact

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - uses: actions/checkout@v4

      - name: List files and create JSON matrix
        id: set-environments
        run: |
          files=$(ls ./configuration | grep 'config\..*\.json' | jq -R . | jq -s -c . |  jq 'map(capture("config\\.(?<environment>[A-Za-z0-9_-]+)\\.json") | .environment)' | jq -c .)
          echo "Files found: $files"
          echo "environments=$files" >> "$GITHUB_OUTPUT"

  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install
        env:
          CI: true

      - run: pnpm --filter "./packages/*" build

      # - run: pnpm run lint
      #   continue-on-error: false

      - run: pnpm --filter cps-global-components test

      # - run: pnpm run test:coverage
      #   continue-on-error: true

      - run: pnpm --filter cps-global-configuration validate

      - run: 'pnpm --filter cps-global-components run rollup --intro ''window.cps_global_components_build = {Sha: "${{ github.sha }}", RunId: "${{ github.run_id }}"};'''

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ${{env.BUILD_ARTIFACT_NAME}}
          path: "./packages/cps-global-components/dist/cps-global-components.*"
          retention-days: 1

  deploy-script:
    needs: [generate-matrix, build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          artifact-ids: ${{needs.build-and-test.outputs.artifact-id}}

      - run: cp ./configuration/config.${{matrix.environment}}.json ${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}/config.json

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage container create \
              --name ${{matrix.environment}} \
              --public-access container \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination ${{matrix.environment}} \
              --source "${{ steps.download.outputs.download-path }}/${{env.BUILD_ARTIFACT_NAME}}" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}" \
              --overwrite \
              --content-cache-control "max-age=20, stale-while-revalidate=3600, stale-if-error=3600" \
              --metadata buildsha=${{ github.sha }} buildrunid=${{ github.run_id }}

  deploy-harnesses:
    needs: generate-matrix
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.generate-matrix.outputs.environments) }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          # Extract our account name from the connection string
          ACCOUNT_NAME=$(echo "${{secrets.BLOB_STORAGE_CONNECTION_STRING}}" | grep -oP 'AccountName=\K[^;]+')

          # Both harnesses look to env variables for the location of the global script
          GLOBAL_SCRIPT_URL="https://$ACCOUNT_NAME.blob.core.windows.net/${{matrix.environment}}/cps-global-components.js"
          echo "GLOBAL_SCRIPT_URL=$GLOBAL_SCRIPT_URL" >> $GITHUB_ENV
          echo "VITE_GLOBAL_SCRIPT_URL=$GLOBAL_SCRIPT_URL" >> $GITHUB_ENV

          # The static harness also needs a BASE_PATH for hyperlinks to be consistent
          echo "BASE_PATH=/${{matrix.environment}}/static" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install
        env:
          CI: true

      - run: pnpm --filter "./apps/**" build

      - uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob delete-batch \
                --source '$web' \
                --pattern "${{matrix.environment}}/static/*" \
                --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination "\$web/${{matrix.environment}}/static" \
              --source "./apps/harness-html/_site" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob delete-batch \
                --source '$web' \
                --pattern "${{matrix.environment}}/spa/*" \
                --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

            az storage blob upload-batch \
              --destination "\$web/${{matrix.environment}}/spa" \
              --source "./apps/harness-spa/dist" \
              --connection-string "${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}"

  repo-security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm audit --audit-level high

      - uses: actions/dependency-review-action@v4

  org-security-scan:
    if: github.event_name == 'pull_request'

    permissions:
      security-events: write
      statuses: write

    uses: CPS-Innovation/.github/.github/workflows/security-scan.yml@main
