name: Node.js CI
on:
  pull_request:
    branches: [main, master] # Runs on PRs targeting main or master branch
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cps-global-header # Set the working directory to the foo subdirectory
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm run build
    - run: pnpm test
