name: "Deploy: all environments including prod"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch is main
        run: |
          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "Error: Production deployments can only be run from the main branch"
            echo "Current branch: ${{ github.ref_name }}"
            exit 1
          fi
          echo "Branch validation passed: running from main branch"

  deploy-all-environments:
    needs: validate-branch
    uses: ./.github/workflows/sub-workflow-core-deploy.yml
    with:
      environments: '["unstable", "accessibility", "dev", "test", "staging", "prod"]'
    secrets:
      BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.BLOB_STORAGE_CONNECTION_STRING }}
