name: "Internal: security scan"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  repo-security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm audit --audit-level high

      - uses: actions/dependency-review-action@v4
